---
- name: Install dependencies for rbenv
  yum: name={{ item }} state=latest
  with_items:
    - git

- name: Install rbenv
  become: yes
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: Add ~.rbenv/bin to PATH
  become: yes
  become_user: "{{ rbenv_user }}"
  lineinfile: >
    dest="~/.bash_profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"

- name: Eval rbenv init in ~/.bash_profile
  become: yes
  become_user: "{{ rbenv_user }}"
  lineinfile: >
    dest="~/.bash_profile"
    line='eval "$(rbenv init -)"'

- name: Install dependencies for ruby-build
  yum: name={{ item }} state=latest
  with_items:
    - gcc-c++
    - glibc-headers
    - openssl-devel
    - libyaml-devel
    - readline-devel
    - zlib-devel
    - libffi-devel
    - libxml2-devel
    - libxslt-devel

- name: Install ruby-build as rbenv plugin
  become: yes
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Check if version is installed ruby
  become: yes
  become_user: {{ rbenv_user }}
  command: rbenv versions | grep {{ rbenv_ruby_version }}
  register: rbenv_check_install
  changed_when: False
  ignore_errors: yes

- name: Install ruby
  become: yes
  become_user: {{ rbenv_user }}
  command: rbenv install {{ rbenv_ruby_version }}
  when: rbenv_check_install|failed

- name: Check if version is the default ruby version
  become: yes
  become_user: {{ rbenv_user }}
  command: rbenv version | grep {{ rbenv_ruby_version }}
  register: rbenv_check_default
  changed_when: False
  ignore_errors: yes

- name: Set default ruby version
  become: yes
  become_user: {{ rbenv_user }}
  command: rbenv global {{ rbenv_ruby_version }}

- name: rbenv rehash
  become: yes
  become_user: {{ rbenv_user }}
  command: rbenv rehash

- name: Install bundler
  become: yes
  become_user: {{ rbenv_user }}
  command: gem install {{ item }}
  with_items:
    - bundler
