---
- name: Install nginx
  yum: name=nginx state=latest

- name: Put nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Put conf.d/rails.conf
  copy: src=rails.conf dest=/etc/nginx/conf.d/rails.conf

- name: Change directory owner
  command: chown -R ec2-user /var/lib/nginx/

- name: Set auto start nginx
  command: chkconfig nginx on

- name: Restart nginx
  service: name=nginx state=restarted
