---
- name: Install nginx
  yum: name=nginx state=latest

- name: Put conf.d/rails.conf
  copy: src=rails.conf dest=/etc/nginx/conf.d/rails.conf

- name: Set auto start nginx
  command: chkconfig nginx on

- name: Restart nginx
  service: name=nginx state=restarted
